sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: MqhLVll0kTgbR2fTBkZ+DgqTsUkzZpxl+qBervHNSRNFdb7HbfRMUfNX9RBxr9b0/odtYFP/y9pRvabyS2+MyyMQlpUfTnJ1G0t27Zp8lohv+HgJT3pkHoWgPhtUaxPPsIzvJdvqbNy2Trj+8/MireUfDE3iL5cePUsJQjxdS+hQu5MopHaMAbEMyklPVKc0QXNKByOvnGT3bnkoAmM3DH4gAJblcIf0Fcg1R+8chny9aaRNmLAKVQOoVbTLS9QeJk2eCKo5ZFZlaw1CMuuxk2D6b0rGE24/RI7aMGWj7w/w3peWBUE+FWQg9uP69tkrDujsmnDcypIgkGCkv7Z9ulREagfpd44v773DlOlv0DXPm+4JEiHXSBztgD44X4RMafVfhtTP8E0m/LWPMYMMh/hQDHR2Y8Qeh2oqEP+bCvbcMY+IuDbqP8eo71r/znTL+XL1dkjEyWTTe6LZgEbFZmUki2iO1sKUwsVb5JjtJ0i8ZUbl7MgYKtPqV/DFunJC+BQ+wspY73TmnrisraO4IyPXX2QFayfqcWPp9B/JRguxfY1PDZ2/+vL6iGyZ3nLR/LnPTwT+MoolTG/XDTIerwUcBruQldz6bMpxNBV4KIqjdZy0ofu72JvGdBMHfIaFF/ZHxXrd0bBUXcIarALupLN1AMK0wI2AguaQsEHjoBw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Days-Before-Yesterday_3827
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy